[package]
name = "console_ui"
version = "0.1.0"
authors.workspace = true
license.workspace = true
license-file.workspace = true
edition.workspace = true

[dependencies]
game_logic = { path = "../game_logic" }
